groups:
- name: django-alerts
  rules:
  - alert: LowBooksInGenre
    expr: books_available{genre!="all"} > 3  
    for: 1m
    labels:
      severity: 'warning'
    annotations:
      summary: "Мало книг в жанре {{ $labels.genre }}"
      description: "В жанре {{ $labels.genre }} осталось {{ $value }} книг"

  - alert: HighRequestLatency
    expr: histogram_quantile(0.95, rate(request_latency_seconds_bucket[1m])) > 1
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: "Высокая задержка для {{ $labels.endpoint }}"
      description: "95-й перцентиль задержки = {{ $value }}s"

  - alert: PostgresHighLoad
    expr: |
      pg_stat_activity_count > 20
      or on()
      (
        pg_stat_database_blks_hit 
        / 
        (pg_stat_database_blks_hit + pg_stat_database_blks_read)
      ) < 0.9
    for: 5m
    labels:
      severity: 'critical'
    annotations:
      summary: "Проблемы с PostgreSQL"
      description: "Активные соединения: {{ $value }}"


