# rule_files:
#   - '/etc/prometheus/alerts.yml'

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']
#       scheme: http
#       timeout: 10s
#       api_version: v2

# scrape_configs:
#   - job_name: 'django'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['django:8000']
#     scheme: http
#     tls_config:
#       insecure_skip_verify: true
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: __param_target
#       - target_label: __address__
#         replacement: django:8000


#   - job_name: 'postgres'
#     static_configs:
#       - targets: ['postgres-exporter:9187']

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - '/etc/prometheus/alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']